name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: ./gradlew build
    - name: github-action-publish-binaries
      uses: skx/github-action-publish-binaries@release-1.3
      with:
        args: build/libs/*-all.jar
